### ISSUE TITLE
Sync failed

### ISSUE THREAD

**Issue by baksosapi** [OpenSRP/opensrp-client-sid#9]
Data from server failed to Fetch.
```
1-13 12:11:52.117 24026-25018/org.smartregister.bidan E/org.smartregister.bidan.sync.ECSyncUpdater: Exception
                                                                                                     java.lang.Exception: /rest/event/sync not returned data
                                                                                                         at org.smartregister.bidan.sync.ECSyncUpdater.fetchAsJsonObject(ECSyncUpdater.java:65)
                                                                                                         at org.smartregister.bidan.sync.ECSyncUpdater.fetchAllClientsAndEvents(ECSyncUpdater.java:74)
                                                                                                         at org.smartregister.bidan.service.intent.SyncIntentService.pullFormAndActionsFromServer(SyncIntentService.java:156)
                                                                                                         at org.smartregister.bidan.service.intent.SyncIntentService.sync(SyncIntentService.java:138)
                                                                                                         at org.smartregister.bidan.service.intent.SyncIntentService.doSync(SyncIntentService.java:97)
                                                                                                         at org.smartregister.bidan.service.intent.SyncIntentService.onHandleIntent(SyncIntentService.java:81)
                                                                                                         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                         at android.os.Looper.loop(Looper.java:158)
                                                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mib-iqbal** [comment]
Related to : https://github.com/OpenSRP/opensrp-client-sid/issues/12
